import java.nio.file.*;
import java.util.*;
import org.objectweb.asm.*;
import org.objectweb.asm.commons.*;
import org.objectweb.asm.tree.*;

/** Execute QoL helpers against native-style fixtures and verify exact DWM selectors. */
public final class TardisQolSmokeTest implements Opcodes {
    public enum Step {NONE,PROCESSING}
    public record Waypoint(String id,TardisShipSmokeTest.Key dimension,TardisShipSmokeTest.Pos blockPos,TardisShipSmokeTest.Dir facing,String name,long timestamp) {}
    public record Packet(Waypoint waypointEntry) {}
    public static class Flight {
        public TardisShipSmokeTest.State tardis;public Step step=Step.PROCESSING;public int tick=164,duration=164;public final List<Waypoint> waypoints=new ArrayList<>();
        public boolean isEnabled(){return true;}public boolean inProgress(){return step!=Step.NONE;}public void addWaypointEntry(Waypoint entry){waypoints.add(entry);}
    }
    public static class QolState extends TardisShipSmokeTest.State {
        public final Flight flight=new Flight();public boolean access=true,attached=true;int accessChecks,dirty;
        @Override public TardisShipSmokeTest.World getWorld(){return attached?world:null;}
        QolState(){flight.tardis=this;}
        public TardisShipSmokeTest.Key getCurrentExteriorDimension(){return world.key;}public TardisShipSmokeTest.Key getDestinationExteriorDimension(){return world.key;}
        public void setDestinationDimension(TardisShipSmokeTest.Key key){}
        public Object getSystem(Class<?> c){return c==Flight.class?flight:mat;}
        public boolean checkAccess(TardisShipSmokeTest.Player player,boolean owner,boolean ignored){accessChecks++;return access;}
        public void method_80(){dirty++;}
    }
    public static class Widget {public boolean field_22763=true,field_22764=true,visible=true,editable=true;public String value="123";public Runnable changed=()->{};public void method_1852(String v){value=v;changed.run();}public void method_25365(boolean v){}public void method_1862(boolean v){visible=v;}public void method_1888(boolean v){editable=v;}public int method_25368(){return 150;}}
    public record Selection(Waypoint waypointEntry) {}
    public static class Screen {public TardisShipSmokeTest.Tag tag;public Selection selected;public Widget xField=new Widget(),yField=new Widget(),zField=new Widget(),nameField=new Widget(),updateButton=new Widget(),resetNameButton=new Widget(),resetXButton=new Widget(),resetYButton=new Widget(),resetZButton=new Widget();}
    public static class CreateScreen {public Screen parentScreen;public TardisShipSmokeTest.Pos originBlockPos;public Widget xField=new Widget(),yField=new Widget(),zField=new Widget(),resetXButton=new Widget(),resetYButton=new Widget(),resetZButton=new Widget();}
    public static class Mount {boolean passenger;public boolean vs$isPassengerSeat(){return passenger;}}
    public static class Rider {Object mount;public Object method_5854(){return mount;}}
    public static class Client {static final Client INSTANCE=new Client();public Rider field_1724;public static Client method_1551(){return INSTANCE;}}
    public static class ShipRegistry {public final Map<Long,Object> all=new HashMap<>();public ShipRegistry getAllShips(){return this;}public Object getById(long id){return all.get(id);} }
    public static class QolUtils extends TardisShipSmokeTest.Utils {static final ShipRegistry registry=new ShipRegistry();public static ShipRegistry getShipObjectWorld(TardisShipSmokeTest.Server server){return registry;} }
    public enum Formatting {field_1055}
    public static class Text extends TardisShipSmokeTest.Text {public String value;public boolean struck;Text(String value){super(value);this.value=value;}public static Text method_43471(String v){return new Text(v);}public Text method_27692(Formatting f){struck=f==Formatting.field_1055;return this;} }
    public static class Texts {public static final Text MONITOR_WAYPOINTS_COORDS=new Text("Coordinates"),MONITOR_WAYPOINT_LOADED=new Text("Waypoint loaded");}
    public static class ListWidget {public Screen parent;}
    public static class Row {public ListWidget this$0=new ListWidget();public Waypoint waypointEntry;}
    public static class DrawContext {public int ordinary,wrapped,width,x,y;public Text message;public int method_51439(Object renderer,Text text,int x,int y,int color,boolean shadow){ordinary++;return 17;}public void method_51440(Object renderer,Text text,int x,int y,int width,int color){wrapped++;this.message=text;this.width=width;this.x=x;this.y=y;} }
    static void check(boolean ok,String message){if(!ok)throw new AssertionError(message);}
    public static void main(String[] args)throws Exception{
        Map<String,String> strings=new HashMap<>();
        String[][] names={{"net.minecraft.class_2561","TardisQolSmokeTest$Text"},{"net.minecraft.class_124","TardisQolSmokeTest$Formatting"},{"net.minecraft.server.MinecraftServer","TardisShipSmokeTest$Server"},{"net.drgmes.dwm.DWM$TEXTS","TardisQolSmokeTest$Texts"},{"net.minecraft.class_243","TardisShipSmokeTest$Vec"},{"net.minecraft.class_2338","TardisShipSmokeTest$Pos"},{"net.minecraft.class_2350","TardisShipSmokeTest$Dir"},{"net.minecraft.class_1937","TardisShipSmokeTest$World"},{"net.minecraft.class_2688","TardisShipSmokeTest$BlockState"},{"net.minecraft.class_4970$class_4971","TardisShipSmokeTest$BlockState"},{"net.minecraft.class_5321","TardisShipSmokeTest$Key"},{"org.valkyrienskies.mod.common.VSGameUtilsKt","TardisQolSmokeTest$QolUtils"},{"net.drgmes.dwm.enums.TardisVerticalScanning","TardisShipSmokeTest$Scanning"},{"net.drgmes.dwm.common.tardis.systems.TardisSystemFlight","TardisQolSmokeTest$Flight"},{"net.drgmes.dwm.common.tardis.systems.flight.TardisFlightWaypointEntry","TardisQolSmokeTest$Waypoint"},{"net.minecraft.class_310","TardisQolSmokeTest$Client"},{"org.valkyrienskies.mod.common.entity.ShipMountingEntity","TardisQolSmokeTest$Mount"}};
        for(String[] n:names)strings.put(n[0],n[1]);strings.put("net.drgmes.dwm.blocks.tardis.consoleunits.screens.TardisConsoleUnitMonitorWaypointsScreen","TardisQolSmokeTest$Screen");
        ClassLoader loader=new ClassLoader(TardisQolSmokeTest.class.getClassLoader()){
            protected Class<?> loadClass(String name,boolean resolve)throws ClassNotFoundException{
                if(!name.startsWith("dev.fan4.compat.doctorwho.")&&!name.startsWith("dev.fan4.compat.jade."))return super.loadClass(name,resolve);
                Class<?> existing=findLoadedClass(name);if(existing!=null)return existing;
                try{ClassWriter w=new ClassWriter(0);new ClassReader(Files.readAllBytes(Path.of(args[0],name.replace('.','/')+".class"))).accept(new ClassRemapper(w,new Remapper(){public Object mapValue(Object value){return value instanceof String s?strings.getOrDefault(s,s):super.mapValue(value);}}),0);byte[] b=w.toByteArray();Class<?> c=defineClass(name,b,0,b.length);if(resolve)resolveClass(c);return c;}catch(Exception e){throw new ClassNotFoundException(name,e);}
            }
        };
        Class<?> h=loader.loadClass("dev.fan4.compat.doctorwho.TardisShipQol"),bridge=loader.loadClass("dev.fan4.compat.doctorwho.TardisShipCompat");
        TardisShipSmokeTest.Utils.ship=new TardisShipSmokeTest.Ship();QolState state=new QolState();state.curr=new TardisShipSmokeTest.Pos(0,70,0);state.dest=new TardisShipSmokeTest.Pos(-2866585,130,9999999);
        var start=h.getMethod("startFlight",Object.class);var update=h.getMethod("updateFlight",Object.class);start.invoke(null,state.flight);update.invoke(null,state.flight);check(state.flight.duration==164,"static ship adds no flight time");
        TardisShipSmokeTest.Utils.ship.matrix.tx+=1000;update.invoke(null,state.flight);check(state.flight.duration>164&&state.flight.tick==state.flight.duration,"receding ship adds time to countdown and total");int extended=state.flight.duration;state.flight.tick-=20;update.invoke(null,state.flight);check(state.flight.duration==extended&&state.flight.tick==extended-20,"unchanged ship does not repeatedly add time");
        TardisShipSmokeTest.Tag tag=new TardisShipSmokeTest.Tag();h.getMethod("writeFlight",Object.class,Object.class).invoke(null,state.flight,tag);h.getMethod("readFlight",Object.class,Object.class).invoke(null,state.flight,tag);TardisShipSmokeTest.Utils.ship.matrix.tx+=1000;update.invoke(null,state.flight);check(state.flight.duration>extended,"reloaded trip preserves frozen departure and accumulated extension");
        state.curr=state.dest;state.flight.step=Step.NONE;
        var display=bridge.getMethod("displayPosition",Object.class,String.class);TardisShipSmokeTest.Pos previous=(TardisShipSmokeTest.Pos)display.invoke(null,state,"prev"),destination=(TardisShipSmokeTest.Pos)display.invoke(null,state,"dest"),current=(TardisShipSmokeTest.Pos)display.invoke(null,state,"curr");TardisShipSmokeTest.Utils.ship.matrix.tx+=100;
        check(((TardisShipSmokeTest.Pos)display.invoke(null,state,"curr")).method_10063()!=current.method_10063(),"current position follows ship");check(((TardisShipSmokeTest.Pos)display.invoke(null,state,"prev")).method_10063()==previous.method_10063(),"same-spot previous remains fixed");check(((TardisShipSmokeTest.Pos)display.invoke(null,state,"dest")).method_10063()==destination.method_10063(),"same-spot destination remains fixed");
        var scanning=h.getMethod("scanning",Object.class,Object.class,Object.class,Object.class);check(scanning.invoke(null,state.mat,state.world,state.curr,TardisShipSmokeTest.Scanning.BOTTOM)==TardisShipSmokeTest.Scanning.DIRECT&&state.mat.scan==TardisShipSmokeTest.Scanning.TOP,"local landing overrides argument without altering scan preference");check(scanning.invoke(null,state.mat,state.world,new TardisShipSmokeTest.Pos(0,0,0),TardisShipSmokeTest.Scanning.BOTTOM)==TardisShipSmokeTest.Scanning.BOTTOM,"ground keeps chosen scan");
        var player=new TardisShipSmokeTest.Player();Waypoint request=new Waypoint("abc",state.world.key,(TardisShipSmokeTest.Pos)display.invoke(null,state,"curr"),TardisShipSmokeTest.Dir.EAST,"Deck",123);
        var add=h.getMethod("addWaypoint",Object.class,Object.class,Object.class);state.access=false;add.invoke(null,state.flight,request,player);check(state.flight.waypoints.isEmpty(),"ship waypoint creation enforces access");state.access=true;add.invoke(null,state.flight,request,player);Waypoint saved=state.flight.waypoints.get(0);check(saved.id().startsWith("fan4compat_ship:42:")&&saved.blockPos()==state.curr,"ship waypoint carries ship ID and local landing address");
        check((Boolean)h.getMethod("immutableWaypoint",Object.class,Object.class,Object.class).invoke(null,state.flight,saved,request),"server rejects ship waypoint edits");Screen screen=new Screen();screen.selected=new Selection(saved);var updateScreen=h.getMethod("updateScreen",Object.class);int[] updates={0};Runnable listener=()->{if(++updates[0]>8)throw new AssertionError("recursive waypoint update");try{updateScreen.invoke(null,screen);}catch(ReflectiveOperationException e){throw new AssertionError(e);}};screen.xField.changed=listener;screen.yField.changed=listener;screen.zField.changed=listener;updateScreen.invoke(null,screen);check(updates[0]==0,"hiding coordinates must not fire DWM text change listeners");check(!screen.xField.visible&&screen.xField.value.equals("123")&&!screen.nameField.editable&&!screen.updateButton.field_22763,"ship waypoint coordinates hidden and editing disabled");
        screen.xField.method_1852("456");check(updates[0]==1&&screen.xField.value.equals("456"),"native text change may refresh the screen once without recursive clearing");
        screen.selected=null;updateScreen.invoke(null,screen);check(updates[0]==1,"ordinary waypoint update does not rewrite text");screen.selected=new Selection(saved);
        TardisShipSmokeTest.Tag sourceTag=new TardisShipSmokeTest.Tag();bridge.getMethod("write",Object.class,Object.class).invoke(null,state,sourceTag);Screen parent=new Screen();parent.tag=new TardisShipSmokeTest.Tag();parent.tag.values.put("tardisTag",sourceTag);CreateScreen creation=new CreateScreen();creation.parentScreen=parent;creation.originBlockPos=TardisShipSmokeTest.Pos.method_10092(sourceTag.method_10537("fan4compatWorld_currPosition"));h.getMethod("rememberCreation",Object.class).invoke(null,creation);h.getMethod("updateCreation",Object.class).invoke(null,creation);check(!creation.xField.visible&&!creation.xField.editable,"ship create screen hides coordinate input");Waypoint opened=new Waypoint("from-screen",state.world.key,creation.originBlockPos,TardisShipSmokeTest.Dir.EAST,"Moving deck",456);TardisShipSmokeTest.Utils.ship.matrix.tx+=500;Waypoint bound=(Waypoint)h.getMethod("createdWaypoint",Object.class,Object.class).invoke(null,creation,opened);add.invoke(null,state.flight,bound,player);check(state.flight.waypoints.size()==2&&bound.blockPos().method_10063()==state.curr.method_10063(),"ship movement while naming waypoint preserves local anchor");
        var apply=h.getMethod("applyWaypoint",Object.class,Object.class,Object.class);state.dest=new TardisShipSmokeTest.Pos(0,0,0);state.access=false;player.message=null;apply.invoke(null,state,new Packet(saved),player);check(state.dest.z==0&&player.message==null,"apply enforces normal access without success message");state.access=true;apply.invoke(null,state,new Packet(saved),player);check(state.dest==state.curr&&player.message==Texts.MONITOR_WAYPOINT_LOADED,"apply restores ship-local position and native Waypoint loaded message");
        Waypoint spoof=new Waypoint(saved.id(),state.world.key,new TardisShipSmokeTest.Pos(999,999,999),TardisShipSmokeTest.Dir.WEST,"spoof",0);apply.invoke(null,state,new Packet(spoof),player);check(state.dest==state.curr,"apply resolves authoritative stored entry");
        TardisShipSmokeTest.Utils.ship=null;state.dest=new TardisShipSmokeTest.Pos(0,0,0);apply.invoke(null,state,new Packet(saved),player);check(state.dest.z==0&&player.message!=null&&player.message!=Texts.MONITOR_WAYPOINT_LOADED,"missing ships do not redirect waypoint onto terrain or show success");TardisShipSmokeTest.Utils.ship=new TardisShipSmokeTest.Ship();
        // Authoritative registry keeps unloaded ships. Position lookups and loaded chunks are irrelevant here.
        QolUtils.registry.all.put(42L,new TardisShipSmokeTest.Ship());
        var write=h.getMethod("writeFlight",Object.class,Object.class);var deleted=h.getMethod("deletedWaypoint",Object.class,Object.class);
        var label=h.getMethod("coordinateLabel",Object.class,Object.class,Object.class,Object.class,int.class,int.class,int.class,boolean.class);
        TardisShipSmokeTest.Tag status=new TardisShipSmokeTest.Tag();write.invoke(null,state.flight,status);
        screen.tag=new TardisShipSmokeTest.Tag();var innerTag=new TardisShipSmokeTest.Tag();screen.tag.values.put("tardisTag",innerTag);innerTag.values.put("TardisSystemFlight",status);
        check(!(Boolean)deleted.invoke(null,screen,saved),"existing unloaded ship is not deleted");
        DrawContext draw=new DrawContext();label.invoke(null,screen,draw,new Object(),Texts.MONITOR_WAYPOINTS_COORDS,12,45,0xffffff,true);check(draw.wrapped==0&&draw.ordinary==0,"available ship hides coordinate label without warning");
        QolUtils.registry.all.remove(42L);write.invoke(null,state.flight,status);check((Boolean)deleted.invoke(null,screen,saved),"deleted ship status reaches screen through native nested flight tag");
        state.attached=false;write.invoke(null,state.flight,status);
        check((Boolean)deleted.invoke(null,screen,saved),"detached-world save preserves last known waypoint status");
        state.attached=true;
        Flight detached=new Flight();write.invoke(null,detached,new TardisShipSmokeTest.Tag());
        Row row=new Row();row.this$0.parent=screen;row.waypointEntry=saved;Text text=new Text(saved.name());Object struck=h.getMethod("waypointText",Object.class,Object.class).invoke(null,row,text);check(struck==text&&text.struck,"deleted ship row name is struck through without changing saved name");
        label.invoke(null,screen,draw,new Object(),Texts.MONITOR_WAYPOINTS_COORDS,12,45,0xffffff,true);check(draw.wrapped==1&&draw.x==12&&draw.y==45&&draw.width==150&&draw.message.value.equals("fan4compat.waypoint.ship_deleted"),"deleted warning wraps at native coordinate area");
        screen.selected=new Selection(request);label.invoke(null,screen,draw,new Object(),Texts.MONITOR_WAYPOINTS_COORDS,12,45,0xffffff,true);check(draw.ordinary==1&&draw.wrapped==1,"ordinary waypoint keeps coordinates");row.waypointEntry=request;Text normal=new Text(request.name());h.getMethod("waypointText",Object.class,Object.class).invoke(null,row,normal);check(!normal.struck,"ordinary waypoint names retain style");
        QolUtils.registry.all.put(99L,new TardisShipSmokeTest.Ship());write.invoke(null,state.flight,status);check((Boolean)deleted.invoke(null,screen,saved),"replacement ship with another ID does not revive old waypoint");
        QolUtils.registry.all.put(42L,new TardisShipSmokeTest.Ship());write.invoke(null,state.flight,status);check(!(Boolean)deleted.invoke(null,screen,saved),"fresh snapshot clears stale unavailable status when same ship exists");
        state.world.field_9236=true;QolUtils.registry.all.clear();write.invoke(null,state.flight,status);check(!(Boolean)deleted.invoke(null,screen,saved),"client cannot overwrite authoritative status using incomplete ship data");state.world.field_9236=false;
        check(saved.name().equals("Deck (Ship)"),"status is display metadata and never rewrites waypoint name or ID");
        var pilot=loader.loadClass("dev.fan4.compat.jade.HelmOverlayCompat").getMethod("piloting");check(!(Boolean)pilot.invoke(null),"Jade visible without player");Client.INSTANCE.field_1724=new Rider();check(!(Boolean)pilot.invoke(null),"Jade visible while walking");Mount mount=new Mount();mount.passenger=true;Client.INSTANCE.field_1724.mount=mount;check(!(Boolean)pilot.invoke(null),"Jade visible for passenger seats");mount.passenger=false;check((Boolean)pilot.invoke(null),"Jade hidden at helm");Client.INSTANCE.field_1724.mount=null;check(!(Boolean)pilot.invoke(null),"Jade restores on dismount");
        if(args.length>1){VerifyAddon.readJar(args[1]);for(String mixin:List.of("TardisShipFlightQolMixin","TardisShipScanningQolMixin","TardisShipControlQolMixin","TardisShipWaypointCreateMixin","TardisShipWaypointApplyMixin")){ClassNode node=new ClassNode();new ClassReader(Files.readAllBytes(Path.of("build/generated/classes/dev/fan4/compat/mixin/doctorwho/common",mixin+".class"))).accept(node,0);VerifyAddon.injectionTargets(node);}ClassNode creationNode=new ClassNode();new ClassReader(Files.readAllBytes(Path.of("build/generated/classes/dev/fan4/compat/mixin/doctorwho/client/TardisShipWaypointCreationQolMixin.class"))).accept(creationNode,0);VerifyAddon.injectionTargets(creationNode);ClassNode screenNode=new ClassNode();new ClassReader(Files.readAllBytes(Path.of("build/generated/classes/dev/fan4/compat/mixin/doctorwho/client/TardisShipWaypointQolMixin.class"))).accept(screenNode,0);VerifyAddon.injectionTargets(screenNode);ClassNode rowNode=new ClassNode();new ClassReader(Files.readAllBytes(Path.of("build/generated/classes/dev/fan4/compat/mixin/doctorwho/client/TardisShipWaypointStatusMixin.class"))).accept(rowNode,0);VerifyAddon.injectionTargets(rowNode);}
        System.out.println("PASS: moving-target time, flight reload, independent displays, temporary scanning, immutable/access-controlled ship waypoints, authoritative apply and helm-only Jade hiding");
    }
}
